config:
  namespace: Game

AudioSettings @not_a_component @json_with_keys:
  masterVolume: [ float, 4. ]

GraphicsSettings @not_a_component @json_with_keys:
  maxArmatureBones: [uint, 64u]
  debugArmatures: [bool, false]
  imGuiFont: [string, "assets/fonts/pixellari/Pixellari.ttf"]
  megaSpriteSheetSize: [uint, 4096] # https://feedback.wildfiregames.com/report/opengl/feature/GL_MAX_TEXTURE_SIZE
  isometricAngle: [float, 30.0f]
  pixelsPerMeter: [uint, 24u]
  cameraDepth: [float, 1000.0f]

KeyInputSettings @not_a_component @json_with_keys:
  moveCameraUp: [KeyInput::Key, GLFW_KEY_W]
  moveCameraLeft: [KeyInput::Key, GLFW_KEY_A]
  moveCameraDown: [KeyInput::Key, GLFW_KEY_S]
  moveCameraRight: [KeyInput::Key, GLFW_KEY_D]
  moveCameraSpeed: [float, 2.0f]
  rotateCameraLeft: [KeyInput::Key, GLFW_KEY_LEFT]
  rotateCameraRight: [KeyInput::Key, GLFW_KEY_RIGHT]
  cancel: [KeyInput::Key, GLFW_KEY_ESCAPE]

  flyCamera: [KeyInput::Key, GLFW_KEY_F]
  stopFlyingCamera: [KeyInput::Key, GLFW_KEY_ESCAPE]
  moveEntity: [ KeyInput::Key, GLFW_KEY_G ]
  gizmoNeedCtrl: [ bool, true ]
  gizmoToggleLocal: [ KeyInput::Key, GLFW_KEY_L ]
  gizmoTranslate: [ KeyInput::Key, GLFW_KEY_T ]
  gizmoRotate: [ KeyInput::Key, GLFW_KEY_Q ]
  gizmoScale: [ KeyInput::Key, GLFW_KEY_S ]

GamepadInputSettings @not_a_component @json_with_keys:
  test: [GamepadInput::Button, GLFW_GAMEPAD_BUTTON_B]

Settings @not_a_component @json_with_keys:
  graphics: GraphicsSettings
  audio: AudioSettings
  keyInput: KeyInputSettings
  gamepadInput: GamepadInputSettings
  customSettings: [ json, json::object() ]
  limitUpdatesPerSec: [ bool, false ]
  showDeveloperOptions: [ bool, false ]
